Repository wecode-bootcamp-korea/48-2nd-Buster_Hot6-frontend, pull requests merged in 2023-08, with the labels that each got.

#1 [48기 정효은] Add :로그인, 회원가입 백엔드랑 통신완료
  package-lock.json
  package.json
  public/images/homelogo.png
  src/App.js
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBar.scss
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.jsx
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#2 [48기 정효은] Home 레이아웃
  public/data/bannerData.json
  public/data/categories.json
  public/data/data.json
  public/images/sand1.jpg
  src/App.js
  src/pages/Home/Home.jsx
  src/pages/Home/components/Banner.jsx
  src/pages/Home/components/Banner.scss
  src/pages/Home/components/Categories.jsx
  src/pages/Home/components/Categories.scss
Labels: Conflict 해결 요청

#5 Feature/cart
  public/data/cart.json
  public/data/cartData.json
  src/App.js
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
  src/pages/Home/components/Categories.jsx
  src/pages/Home/components/Categories.scss
Labels: Conflict 해결 요청

#4 ADD: 캐러셀 UI
  package-lock.json
  package.json
  src/App.js
  src/components/Address/Address.jsx
  src/components/Address/Address.scss
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.scss
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.scss
  src/components/OrderProduct/OrderProduct.jsx
  src/components/OrderProduct/OrderProduct.scss
  src/components/OrderProductCard/OrderProductCard.jsx
  src/components/OrderProductCard/OrderProductCard.scss
  src/components/OrderProductPayment/OrderProductPayment.jsx
  src/components/OrderProductPayment/OrderProductPayment.scss
  src/components/OrderSidebar/OrderSidebar.jsx
  src/components/OrderSidebar/OrderSidebar.scss
  src/components/PaymentContainer/PaymentContainer.jsx
  src/components/PaymentContainer/PaymentContainer.scss
  src/components/ProductItemDetail/ProductItemDetail.jsx
  src/components/ProductItemDetail/ProductItemDetail.scss
  src/components/ProductItemDetailInfo/ProductItemDetailInfo.jsx
  src/components/ProductItemDetailInfo/ProductItemDetailInfo.scss
  src/components/ProductItemTap/ProductItemTap.jsx
  src/components/ProductItemTap/ProductItemTap.scss
  src/components/Products/ProductCard.jsx
  src/components/Products/ProductCard.scss
  src/components/Products/ProductList.jsx
  src/components/Products/ProductList.scss
  src/components/Products/ProductListCard.jsx
  src/components/Products/ProductListCard.scss
  src/components/ProductsCarousel/ProductsCarousel.jsx
  src/components/ProductsCarousel/ProductsCarousel.scss
  src/components/ProductsSlide/ProductsSlide.jsx
  src/components/ProductsSlide/ProductsSlide.scss
  src/components/ReviewModal/ReviewModal.jsx
  src/components/ReviewModal/ReviewModal.scss
  src/components/Reviews/Reviews.jsx
  src/components/Reviews/Reviews.scss
  src/hooks/useInterval.jsx
  src/pages/HomeDetail/HomeDetail.jsx
  src/pages/HomeDetail/HomeDetail.scss
  src/pages/Orders/Orders.jsx
  src/pages/Orders/Orders.scss
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/Products/Products.jsx
  src/pages/Products/Products.scss
  src/pages/Store/Store.jsx
  src/pages/Store/Store.scss
Labels: Conflict 해결 요청, 수정 요청
